# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-28 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='music',
            field=models.CharField(default='null', max_length=300),
        ),
        migrations.AddField(
            model_name='blog',
            name='reading_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.CharField(default='null@null.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcomment',
            name='email',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
