# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-31 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=4000)),
                ('content_time', models.DateTimeField()),
                ('modify_time', models.DateTimeField()),
                ('page_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DutyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_time', models.DateTimeField()),
                ('duty_leader', models.CharField(max_length=128)),
                ('duty_man', models.CharField(max_length=128)),
                ('duty_manager', models.CharField(max_length=128)),
                ('duty_proxy', models.CharField(max_length=128)),
                ('date', models.CharField(default='2017-1-1', max_length=128)),
                ('weekday', models.CharField(default='NULL', max_length=128)),
                ('weather', models.CharField(max_length=128)),
                ('temp', models.CharField(max_length=128)),
                ('page_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InstructionTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.CharField(max_length=4000)),
                ('instruction_time', models.DateTimeField()),
                ('modify_time', models.DateTimeField()),
                ('page_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProxyInstructionTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_instruction', models.CharField(max_length=4000)),
                ('proxy_instruction_time', models.DateTimeField()),
                ('modify_time', models.DateTimeField()),
                ('page_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ResultTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=4000)),
                ('result_time', models.DateTimeField()),
                ('modify_time', models.DateTimeField()),
                ('page_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RoleTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('roleflag', models.CharField(max_length=128)),
            ],
        ),
    ]
