# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-28 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=4000)),
                ('content_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DutyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_leader', models.CharField(max_length=128)),
                ('duty_man', models.CharField(max_length=128)),
                ('duty_manager', models.CharField(max_length=128)),
                ('duty_driver', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='InstructionTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.CharField(max_length=4000)),
                ('instruction_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ResultTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=4000)),
            ],
        ),
    ]
