# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-28 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DutyLog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenttable',
            name='dutyinfo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DutyLog.DutyInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructiontable',
            name='dutyinfo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DutyLog.DutyInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resulttable',
            name='dutyinfo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DutyLog.DutyInfo'),
            preserve_default=False,
        ),
    ]
