# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-28 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DutyLog', '0002_auto_20170129_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyInstructionTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_instruction', models.CharField(max_length=4000)),
                ('proxy_instruction_time', models.DateTimeField()),
                ('modify_time', models.DateTimeField()),
                ('page_no', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='dutyinfo',
            old_name='duty_driver',
            new_name='duty_proxy',
        ),
        migrations.RemoveField(
            model_name='contenttable',
            name='dutyinfo',
        ),
        migrations.RemoveField(
            model_name='instructiontable',
            name='dutyinfo',
        ),
        migrations.RemoveField(
            model_name='resulttable',
            name='dutyinfo',
        ),
        migrations.AddField(
            model_name='contenttable',
            name='modify_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contenttable',
            name='page_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dutyinfo',
            name='page_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructiontable',
            name='modify_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructiontable',
            name='page_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resulttable',
            name='modify_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resulttable',
            name='page_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resulttable',
            name='result_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
