# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-29 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DutyLog', '0003_auto_20170129_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('roleflag', models.IntegerField()),
            ],
        ),
    ]
