# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-29 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DutyLog', '0005_auto_20170129_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutyinfo',
            name='date',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dutyinfo',
            name='temp',
            field=models.CharField(default=18, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dutyinfo',
            name='weather',
            field=models.CharField(default='null', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dutyinfo',
            name='weekday',
            field=models.CharField(default='\u661f\u671f\u4e00', max_length=128),
            preserve_default=False,
        ),
    ]
