# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-30 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DutyLog', '0006_auto_20170130_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutyinfo',
            name='duty_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
