# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-28 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='ip',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
